apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-deploy
  name: app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-deploy
    spec:
      containers:
        - image: louiskimlevu/bb-app:v3
          name: bb-app
          ports:
            - containerPort: 5000
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-deploy
  name: bbphoenix
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: app-deploy
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lklvingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bbphoenix
                port:
                  number: 80
